export const GET_ALL_CAREERS = "GET_ALL_CAREERS";

export const CAREERS_START = "CAREERS_START";
export const CAREERS_ERROR = "CAREERS_ERROR";
export const CAREERS_PAGE_NUMBER = "CAREERS_PAGE_NUMBER";
export const CAREER_APPLICATION = "CAREER_APPLICATION";
export const CAREER_INTERESTNG = "CAREER_INTERESTNG";



export const SEARCH_VALIU = "SEARCH_VALIU";
export const SEARCH_RESULT = "SEARCH_RESULT";

//partners
export const GET_PARTNERS = "GET_PARTNERS";
export const PARTNERS_LOADING = "PARTNERS_LOADING";
export const PARTNERS_ERROR = "PARTNERS_ERROR";
