// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../layouts/landing";
import HomeHero from "../components/home/hero";
import Companies from "../components/home/companies";
import OurWork from "../components/home/ourWork";
import WhyChooseUs from "../components/home/whyChooseUs";
import Services from "../components/home/services";
import WorkWith from "../components/home/workWith";
import HomeContact from "../components/home/homeContact";
import HomeInsight from "../components/home/homeInsight";
import ScrollAnimation from 'react-animate-on-scroll';

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomeHero />
      <Companies />
      <OurWork />
      <ScrollAnimation animateIn="fadeIn" duration={.8} delay={400} animateOnce={true}><WhyChooseUs /></ScrollAnimation>
      <Services />
      <ScrollAnimation animateIn="fadeIn" duration={.8} delay={400} animateOnce={true}><WorkWith heading="Working With Cloudfift" /></ScrollAnimation>
      <HomeContact />
      <ScrollAnimation animateIn="fadeIn" duration={.8} delay={400} animateOnce={true}><HomeInsight /></ScrollAnimation>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
